#!/bin/sh
echo "🔎 Checking types..."
bun run type:check
echo "✅ Types are ok"

echo "\n"

echo "🔎 Linting files..."

if echo "$(bun run lint 2>&1)" | grep -q 'src/'; then
  bun run lint
  exit 1
else
  echo "✅ Linting is ok"
fi
