#!/bin/sh
echo "🔎 Checking types..."
tsc --noEmit
echo "✅ Types are ok"

echo ""

echo "🔎 Linting files..."
if biome check src/ 2>&1 | grep -q 'src/'; then
  biome check src/
  exit 1
else
  echo "✅ Linting is ok"
fi
